wds_doctrine_crud_api_create: &wds_doctrine_crud_api_create_with_slash
    path:     /{entityName}/create/
    methods:  [ OPTIONS, POST ]
    controller: WernerDweight\DoctrineCrudApiBundle\Controller\CreateController::index
    defaults:
        _format: json

wds_doctrine_crud_api_create_without_slash:
    <<: *wds_doctrine_crud_api_create_with_slash
    path: /{entityName}/create
    defaults:
        _route_override: wds_doctrine_crud_api_create

wds_doctrine_crud_api_delete: &wds_doctrine_crud_api_delete_without_slash
    path:     /{entityName}/delete/{id}
    methods:  [ OPTIONS, DELETE ]
    controller: WernerDweight\DoctrineCrudApiBundle\Controller\DeleteController::index
    defaults:
        _format: json

wds_doctrine_crud_api_delete_with_slash:
    <<: *wds_doctrine_crud_api_delete_without_slash
    path: /{entityName}/delete/{id}/
    defaults:
        _route_override: wds_doctrine_crud_api_delete

wds_doctrine_crud_api_detail:
    path:     /{entityName}/detail/{id}
    methods:  [ OPTIONS, GET ]
    controller: WernerDweight\DoctrineCrudApiBundle\Controller\DetailController::index
    defaults:
        _format: json

wds_doctrine_crud_api_length:
    path:     /{entityName}/length/
    methods:  [ OPTIONS, GET ]
    controller: WernerDweight\DoctrineCrudApiBundle\Controller\LengthController::index
    defaults:
        _format: json

wds_doctrine_crud_api_list:
    path:     /{entityName}/list/
    methods:  [ OPTIONS, GET ]
    controller: WernerDweight\DoctrineCrudApiBundle\Controller\ListController::index
    defaults:
        _format: json

wds_doctrine_crud_api_update: &wds_doctrine_crud_api_update_without_slash
    path:     /{entityName}/update/{id}
    methods:  [ OPTIONS, POST ]
    controller: WernerDweight\DoctrineCrudApiBundle\Controller\UpdateController::index
    defaults:
        _format: json

wds_doctrine_crud_api_update_with_slash:
    <<: *wds_doctrine_crud_api_update_without_slash
    path: /{entityName}/update/{id}/
    defaults:
        _route_override: wds_doctrine_crud_api_update
